# Generated by Django 5.2.11 on 2026-02-13 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('opcion_a', models.CharField(max_length=100)),
                ('opcion_b', models.CharField(max_length=100)),
                ('opcion_c', models.CharField(max_length=100)),
                ('correcta', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C')], max_length=1)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.examen')),
            ],
        ),
    ]
